urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from os import path as os_path

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^sequias/', include('sequias.foo.urls')),
    (r'^', include('sequias.urls')),
    (r'^$', 'sequias.views.index'),
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    url(r'^chaining/', include('smart_selects.urls')),
)

handler500 = 'sequias.views.file_not_found_500'

if (settings.DEBUG == True):
    urlpatterns += patterns('',
                            (r'^media/(.*)$', 'django.views.static.serve', {'document_root': os_path.join(settings.MEDIA_ROOT)}),
                        )

sequias/forms.py
 # -*- coding: UTF-8 -*-

from django import forms
from django.forms import ModelForm
from sequias.models import *
from lugar.models import *

date_inputformats=['%d.%m.%Y','%d/%m/%Y','%Y-%m-%d']

class SequiaForm(forms.Form):
    fecha_inicio = forms.DateField(input_formats=date_inputformats)
    fecha_final = forms.DateField(input_formats=date_inputformats)
    departamento = forms.ModelChoiceField(queryset=Departamento.objects.all(), required=False, empty_label="Todos los Departamentos")
    municipio = forms.CharField(widget = forms.Select, required=False)
    comunidad = forms.CharField(widget = forms.Select, required=False)
    entrevistado = forms.CharField(widget = forms.Select, required=False)
    

templates/base.html
<!doctype html>
<html>
  <head>
    <title>{% block title %}Sondeo de Sequia{% endblock %}</title>
    <link rel="stylesheet" href="/media/css/themes/default/default.css" type="text/css" media="screen" />
    <link href="/media/css/style.css" rel="stylesheet" />
    <link href="/media/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/media/css/nivo-slider.css" rel="stylesheet" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
    <script type="text/javascript" src="/media/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/media/js/jquery.nivo.slider.js"></script> 

   <script type="text/javascript">
     $(window).load(function() {
         $('#slider').nivoSlider();
     });
   </script>

{% block extraheader %}{% endblock %}
{% block extra_js %}{% endblock %}
  </head>
<body>
<div class="container">  <!-- empieza la clase container -->

	<div id="header"> <!-- empieza el header -->
    <a href="/">
		<img src="/media/imagen/prueba.png" width=106 height=78 alt="gpae"/>  <p class="mover">Sondeo sobre impacto de la sequia en Nicaragua</p></a>
	</div> <!-- termina el header --> 


<br>
{% block menu %}
<div class="navbar">
  <div class="navbar-inner">    
    <ul class="nav">
      <li class="active"><a href="/">Inicio</a></li>
      <li><a href="/index">Consultar</a></li>
      <li class="dropdown">
        <a class="dropdown-toggle"
            data-toggle="dropdown"
            href="#">
            Extras
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="/general"><i class="icon-search"></i> Datos generales</a></li>
            <li class="divider"></li>
            <li><a href="/admin"><i class="icon-user"></i> Administración</a></li>
        </ul>
    </li>
    </ul>
  </div>
</div>
{% endblock %}

{% block content %}

			<div class="slider-wrapper theme-default">
					<div id="slider" class="nivoSlider">
						<img src="/media/imagen/frijol.jpg" alt="frijol" title="#captionfrijol"/>
				
          	<img src="/media/imagen/maiz.jpg" alt="maiz" title="#captionmaiz"/>
				
          	<img src="/media/imagen/sorgo1.jpg" alt="sorgo" title="#captionsorgo"/>
      		</div>
          <div id="captionfrijol" class="nivo-html-caption">
                <strong>El Frijol</strong><br />Es una planta originaria de América que se cultiva en todo el mundo. Existen numerosas variedades y de ellas se consumen tanto las vainas verdes (judía verde o chauchas) como los granos secos.
          </div>
          <div id="captionmaiz" class="nivo-html-caption">
                <strong>El Maíz</strong><br />Es una gramínea anual originaria de las Américas introducida en Europa en el siglo XVI. Actualmente, es el cereal con mayor volumen de producción en el mundo, superando al trigo y el arroz.
          </div>
          <div id="captionsorgo" class="nivo-html-caption">
                <strong>El Sorgo</strong><br />Género botánico de unas 20 especies de gramíneas oriundas de las regiones tropicales y subtropicales de África oriental.
          </div>
   				
			</div>

{% endblock %}

        <div class="navbar">
          <div class="navbar-inner"> 
                  <ul>
                  <p class="piepagina"><a href="http://www.simas.org.ni">SIMAS 2009</a></p>
                  </ul>
          </div>
        </div>


</div> <!-- termina clase container -->

</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block extra_js %}
<link rel="stylesheet" href="/media/css/jquery-ui-1.7.2.custom.css" />
<script type="text/javascript" src="/media/js/jquery-ui-1.7.2.custom.min.js"></script>

<script type="text/javascript">
        $(document).ready(function() {

        $("#id_fecha_inicio").datepicker({ dateFormat: 'yy-mm-dd', dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'], monthNamesShort: ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],yearRange:"2009:2015",changeMonth: true, changeYear: true});

        $("#id_fecha_final").datepicker({ dateFormat: 'yy-mm-dd', dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'], monthNamesShort: ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],yearRange:"2009:2015",changeMonth: true, changeYear: true});

        var departamento = document.getElementById("id_departamento");
        var municipio = document.getElementById("id_municipio");
        var comunidad= document.getElementById("id_comunidad");
        var entrevistado = document.getElementById("id_entrevistado");
        $("#id_departamento").change(function () {
            var index = departamento.options.selectedIndex;
            var id = departamento.options[index].value;
            $.getJSON("/ajax/municipio/" + id +"/",
            function(data){
                municipio.options.length = 0;
                comunidad.options.length = 0;
                municipio.options[0] = new Option("--------");
                for(i=0; i< data.length; i++){
                    municipio.options[i+1] = new Option(data[i][1], data[i][0]);
                }
            });
        });
        $("#id_municipio").change(function () {
            var index = municipio.options.selectedIndex;
            var id = municipio.options[index].value;
            $.getJSON("/ajax/comunidad/" + id +"/",
            function(data){
                comunidad.options.length = 0;
                comunidad.options[0] = new Option("---------");
                for(i=0; i< data.length; i++){
                    comunidad.options[i+1] = new Option(data[i][1], data[i][0]);
                }
            });
        });
        $("#id_comunidad").change(function () {
            var index = comunidad.options.selectedIndex;
            var id = comunidad.options[index].value;
            $.getJSON("/ajax/entrevista/" + id +"/",
            function(data){
                entrevistado.options.length = 0;
                entrevistado.options[0] = new Option("---------");
                for(i=0; i< data.length; i++){
                    entrevistado.options[i+1] = new Option(data[i][1], data[i][0]);
                }
            });
        });
 });
</script>

{% endblock %}

{% block menu %} 
<div class="navbar">
  <div class="navbar-inner">    
    <ul class="nav">
    <li><a href="/index">Consultar</a></li>
    <li><a href="/perdida">Pérdidas</a></li>
    <li><a href="/disponibilidad">Disponibilidad</a></li>
    <li><a href="/nutricion">Nutrición</a></li>
    <li class="dropdown">
        <a class="dropdown-toggle"
            data-toggle="dropdown"
            href="#">
            Extras
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li><a href="/descargar/xls"><i class="icon-folder-open"></i> hoja XLS</a></li>
            <li><a href="/descargar/word"><i class="icon-pencil"></i> Reporte</a></li>
            <li class="divider"></li>
            <li><a href="/admin"> <i class="icon-user"></i> Administración</a></li>
        </ul>
    </li>

</ul>
  </div>
</div>
{% endblock %}

{% block content %}

{% if mensaje%}
{% block bread%}
        <ul class="breadcrumb">
            {% if request.session.departamento%}
            <li>Departamento:<i>{{ request.session.departamento.nombre }}</i> <span class="divider">/</span></li>
            {%endif%}
            {% if request.session.municipio%}
            <li>Municipio:<i> {{request.session.municipio.nombre}}</i> <span class="divider">/</span></li>
            {%endif%}
            {% if request.session.comunidad%}
            <li>Comunidad:<i> {{request.session.comunidad.nombre}}</i> <span class="divider">/</span></li>
            {%endif%}
            {% if request.session.entrevistado%}
            <li>Entrevistado: <i> {{ request.session.entrevistado.nombre }}</i></li>
            {%endif%}
        </ul>
{%endblock%}
{%endif%}

{%if mensaje%}
  <div class="alert alert-success">
    {{mensaje}}
  </div>
{%endif%}

<form class="form-horizontal" action"." method="POST">{% csrf_token %}

  <legend>Consultar</legend>
  <div class="control-group">
    <label class="control-label" for="inputFechaInicio">{{form.fecha_inicio.label}}</label>
    <div class="controls">
      <div class="datepicker">
           {{form.fecha_inicio}}
       </div> 
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputFechaFinal">{{form.fecha_final.label}}</label>
    <div class="controls">
       <div class="datepicker">
            {{form.fecha_final}}
       </div>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputDepartamento">{{form.departamento.label}}</label>
    <div class="controls">
      {{form.departamento}}
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputMunicipio">{{form.municipio.label}}</label>
    <div class="controls">
      {{form.municipio}}
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputComunidad">{{form.comunidad.label}}</label>
    <div class="controls">
      {{form.comunidad}}
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputEntrevistado">{{form.entrevistado.label}}</label>
    <div class="controls">
      {{form.entrevistado}}
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">Consultar</button>
    </div>
  </div>

</form>


{% endblock %}